import {
  Injectable,
  InternalServerErrorException,
  Logger,
} from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { CreateReportDto } from './dto/create-report.dto';

@Injectable()
export class ReportsService {
  private readonly logger = new Logger(ReportsService.name);

  constructor(private readonly prisma: PrismaService) {}

  /**
   * Persist a new daily report generated by the Python AI engine.
   */
  async createReport(userId: string, dto: CreateReportDto) {
    try {
      const report = await this.prisma.dailyReport.create({
        data: {
          summary: dto.summary,
          totalIncidents: dto.totalIncidents,
          criticalAlerts: dto.criticalAlerts,
          peakActivityHour: dto.peakActivityHour,
          averageThreatLevel: dto.averageThreatLevel,
          userId,
        },
      });

      this.logger.log(
        `📋 Daily report created: ${report.id} ` +
          `(${dto.totalIncidents} incidents, peak hour: ${dto.peakActivityHour}h)`,
      );

      return report;
    } catch (error) {
      this.logger.error('Failed to create daily report', error);
      throw new InternalServerErrorException(
        'Could not save the daily report. Please try again.',
      );
    }
  }

  /**
   * Return the last 7 daily reports for the authenticated user,
   * sorted by most recent first.
   */
  async getWeeklyHistory(userId: string) {
    try {
      return await this.prisma.dailyReport.findMany({
        where: { userId },
        orderBy: { createdAt: 'desc' },
        take: 7,
      });
    } catch (error) {
      this.logger.error('Failed to fetch weekly report history', error);
      throw new InternalServerErrorException(
        'Could not retrieve report history. Please try again.',
      );
    }
  }
}
